#!/bin/bash
export OMP_NUM_THREADS=1
export HIP_VISIBLE_DEVICES=0,1,2,3,4,5,6
torchrun \
    --nnodes=1 \
    --nproc_per_node=7 \
    ../../train.py \
    --name="nano_l0" \
    --train_file="/public/onestore/onedatasets/MaterialsChemistry/examples/nanotube/nanotube_large.xyz" \
    --valid_fraction=0.05 \
    --test_file="/public/onestore/onedatasets/MaterialsChemistry/examples/nanotube/nanotube_test.xyz" \
    --E0s="average" \
    --model="MACE" \
    --num_interactions=2 \
    --num_channels=256 \
    --max_L=0 \
    --correlation=3 \
    --r_max=6.0 \
    --forces_weight=1000 \
    --energy_weight=10 \
    --energy_key="Energy" \
    --forces_key="forces" \
    --batch_size=4 \
    --valid_batch_size=8 \
    --max_num_epochs=100 \
    --start_swa=600  \
    --scheduler_patience=5 \
    --patience=15 \
    --eval_interval=3 \
    --ema \
    --swa \
    --distributed \
    --swa_forces_weight=10 \
    --error_table='PerAtomMAE' \
    --default_dtype="float64"\
    --device=cuda \
    --seed=123 \
    --restart_latest \
    --save_cp
