#!/bin/bash
export OMP_NUM_THREADS=1
export HIP_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
source ../../../../../env.sh
torchrun \
    --nnodes=1 \
    --nproc_per_node=8 \
    ../../train.py \
    --name="ani1x" \
    --train_file="${ONESCIENCE_DATASETS_DIR}/MaterialsChemistry/examples/ani1x/ANI1x_cc_DFT_rc5_train" \
    --valid_fraction=0.05 \
    --test_file="${ONESCIENCE_DATASETS_DIR}/MaterialsChemistry/examples/ani1x/ANI1x_cc_DFT_rc5_test" \
    --valid_file="${ONESCIENCE_DATASETS_DIR}/MaterialsChemistry/examples/ani1x/ANI1x_cc_DFT_rc5_val" \
    --statistics_file="${ONESCIENCE_DATASETS_DIR}/MaterialsChemistry/examples/ani1x/ANI1x_cc_DFT_rc5_statistics.json" \
    --E0s="average" \
    --model="MACE" \
    --num_interactions=2 \
    --num_channels=64 \
    --max_L=0 \
    --correlation=3 \
    --r_max=6.0 \
    --forces_weight=1000 \
    --energy_weight=10 \
    --energy_key="TolEnergy" \
    --forces_key="force" \
    --batch_size=2 \
    --valid_batch_size=4 \
    --max_num_epochs=10 \
    --scheduler_patience=15 \
    --patience=30 \
    --eval_interval=4 \
    --ema \
    --swa \
    --distributed \
    --error_table='PerAtomMAE' \
    --default_dtype="float64"\
    --device=cuda \
    --seed=123 \
    --save_cp
