import click
from ..core.registry import model_registry, DOMAIN_DESCRIPTIONS


_GROUPED_ALIASES: dict[str, list[tuple[str, str]]] = {}
for m in model_registry.list_models():
    domain_desc = m["domain_desc"]
    if domain_desc not in _GROUPED_ALIASES:
        _GROUPED_ALIASES[domain_desc] = []
    _GROUPED_ALIASES[domain_desc].append((m["alias"], m["model"]))


@click.command("help")
@click.pass_context
def help_cmd(ctx):
    """显示帮助信息"""
    click.secho("OneScience 命令工具", fg="green")
    click.echo("用法: onescience <command> [options]")
    click.echo("")
    click.echo("命令:")
    click.echo("  bench     - 使用指定数据集运行多个模型（训练+推理+评估）")
    click.echo("  train     - 仅执行模型训练")
    click.echo("  infer     - 仅执行模型推理")
    click.echo("  eval      - 仅执行模型评估")
    click.echo("  REMOCK    - 重置模型环境")
    click.echo("  log       - 查看模型日志")
    click.echo("  status    - 查看模型执行状态")
    click.echo("  list      - 列出可用资源")
    click.echo("    models  - 列出所有可用模型")
    click.echo("    modules - 列出所有可用模块")
    click.echo("    datasets - 列出所有可用数据集")
    click.echo("    datasets -full - 扫描实际数据集目录的详细内容")
    click.echo("  info      - 显示资源详细信息")
    click.echo("    module  - 显示模块信息或代码")
    click.echo("  config    - 查看或修改配置")
    click.echo("    show    - 查看当前配置")
    click.echo("    set     - 修改配置项")
    click.echo("  help      - 显示此帮助信息")
    click.echo("")
    click.echo("参数:")
    click.echo("  -dataset <数据集>  - 指定要使用的数据集（可以是名称或完整路径）")
    click.echo("  -models <模型列表> - 指定要执行的模型，用逗号分隔")
    click.echo("")
    click.echo("list 命令选项:")
    click.echo("  onescience list models [-domain <领域>] [-model <模型>] [-all] [-format <table|json|csv>]")
    click.echo("    -domain    - 按领域筛选模型（earth/cfd/biosciences/MaterialsChemistry）")
    click.echo("    -model     - 按模型别名筛选")
    click.echo("    -all       - 显示详细信息（包含模型描述）")
    click.echo("    -format    - 输出格式（默认 table）")
    click.echo("")
    click.echo("  onescience list modules [-type <类型>] [-all] [-format <table|json|csv>]")
    click.echo("    -type      - 按类型筛选")
    click.echo("    -all       - 显示详细信息")
    click.echo("    -format    - 输出格式（默认 table）")
    click.echo("")
    click.echo("log 命令选项:")
    click.echo("  onescience log <模型别名1>[,<模型别名2>,...] [选项]")
    click.echo("    -tail <行数>    - 显示日志末尾指定行数（默认 50）")
    click.echo("    -head <行数>    - 显示日志开头指定行数")
    click.echo("    -search <关键词> - 搜索日志中包含指定关键词的行")
    click.echo("    -all           - 显示完整日志内容")
    click.echo("    -type <类型>    - 指定日志类型（train/infer/eval/all）")
    click.echo("    -follow        - 实时跟踪日志更新（tail -f）")
    click.echo("    -date <日期>   - 查看指定日期的日志（格式：YYYY-MM-DD）")
    click.echo("    -clean <天数>  - 清理指定天数前的旧日志")
    click.echo("")
    click.echo("提示:")
    click.echo("  - 输入数据集名称时，会使用默认路径查找数据集")
    click.echo("  - 输入完整路径时，会直接使用指定的路径")
    click.echo("  - 确保当前账号对指定的数据集路径有访问权限")
    click.echo("")
    click.secho("支持的模型别名:", fg="green")
    for domain_desc, aliases in _GROUPED_ALIASES.items():
        click.secho(f"\n[{domain_desc}]", fg="cyan")
        for alias, model_name in aliases:
            click.echo(f"  {alias:<20} - {model_name}")
    click.echo("  (也支持直接使用模型目录名)")
    click.echo("")
    click.echo("示例:")
    click.echo("  onescience bench -dataset era5 -models pangu,fuxi,mace")
    click.echo("  onescience train pangu -dataset era5          - 仅训练模型")
    click.echo("  onescience infer pangu -dataset era5          - 仅执行推理")
    click.echo("  onescience eval pangu -dataset era5           - 仅执行评估")
    click.echo("  onescience list models                       - 列出所有模型")
    click.echo("  onescience list models -domain earth -all    - 列出气象领域所有模型")
    click.echo("  onescience list modules                      - 列出所有模块")
    click.echo("  onescience list datasets                     - 列出所有可用数据集")
    click.echo("  onescience list datasets -full               - 扫描数据集目录详细内容")
    click.echo("  onescience info module attention             - 显示 attention 模块信息")
    click.echo("  onescience status pangu                      - 查看模型执行状态")
    click.echo("  onescience config show                       - 查看当前配置")
    click.echo("  onescience config set data_dir /path         - 修改数据集路径")
    click.echo("  onescience log pangu                         - 查看 pangu 模型日志")
    click.echo("  onescience log pangu -clean 7                - 清理7天前的旧日志")
