import click
from ..core.registry import model_registry, DOMAIN_DESCRIPTIONS


@click.command("help")
@click.pass_context
def help_cmd(ctx):
    """显示帮助信息"""
    _GROUPED_ALIASES: dict[str, list[tuple[str, str]]] = {}
    for m in model_registry.list_models():
        domain_desc = m["domain_desc"]
        if domain_desc not in _GROUPED_ALIASES:
            _GROUPED_ALIASES[domain_desc] = []
        _GROUPED_ALIASES[domain_desc].append((m["alias"], m["model"]))
    click.secho("OneScience 命令工具", fg="green")
    click.echo("用法: onescience <command> [options]")
    click.echo("")
    click.echo("命令:")
    click.echo("  bench     - 使用指定数据集运行多个模型（训练+推理+评估）")
    click.echo("  train     - 仅执行模型训练")
    click.echo("  infer     - 仅执行模型推理")
    click.echo("  eval      - 仅执行模型评估")
    click.echo("  REMOCK    - 重置模型环境")
    click.echo("  log       - 查看模型日志")
    click.echo("  status    - 查看模型执行状态")
    click.echo("  list      - 列出可用资源")
    click.echo("    models  - 列出所有可用模型")
    click.echo("    modules - 列出所有可用模块")
    click.echo("    datasets - 列出所有可用数据集")
    click.echo("    datasets -full - 扫描实际数据集目录的详细内容")
    click.echo("  info      - 显示资源详细信息")
    click.echo("    module  - 显示模块信息或代码")
    click.echo("  config    - 查看或修改配置")
    click.echo("    show    - 查看当前配置")
    click.echo("    set     - 修改配置项")
    click.echo("  compare   - 对比多个模型的执行结果（从已保存的结果中加载）")
    click.echo("  pipeline  - 编排并执行多步骤工作流，跨领域混合调度")
    click.echo("  data      - 数据准备与管理")
    click.echo("    list    - 列出所有可用数据集")
    click.echo("    info    - 显示数据集详情")
    click.echo("    download - 下载数据集（如 ERA5）")
    click.echo("    generate - 生成模型的假数据")
    click.echo("  deploy    - 模型部署")
    click.echo("    export  - 导出模型为 ONNX 格式")
    click.echo("    serve   - 启动 Triton 推理服务")
    click.echo("  experiment - 实验管理")
    click.echo("    list    - 列出实验记录")
    click.echo("    info    - 查看实验详情")
    click.echo("  env       - 环境管理（项目切换与配置）")
    click.echo("    list    - 列出可用环境")
    click.echo("    use     - 切换到指定环境")
    click.echo("    init    - 初始化新项目")
    click.echo("    info    - 显示当前环境详情")
    click.echo("  help      - 显示此帮助信息")
    click.echo("")
    click.echo("参数:")
    click.echo("  -dataset <数据集>  - 指定要使用的数据集（可以是名称或完整路径）")
    click.echo("  -models <模型列表> - 指定要执行的模型，用逗号分隔")
    click.echo("")
    click.echo("list 命令选项:")
    click.echo("  onescience list models [-domain <领域>] [-model <模型>] [-all] [-format <table|json|csv>]")
    click.echo("    -domain    - 按领域筛选模型（earth/cfd/biosciences/MaterialsChemistry）")
    click.echo("    -model     - 按模型别名筛选")
    click.echo("    -all       - 显示详细信息（包含模型描述）")
    click.echo("    -format    - 输出格式（默认 table）")
    click.echo("")
    click.echo("  onescience list modules [-type <类型>] [-all] [-format <table|json|csv>]")
    click.echo("    -type      - 按类型筛选")
    click.echo("    -all       - 显示详细信息")
    click.echo("    -format    - 输出格式（默认 table）")
    click.echo("")
    click.echo("log 命令选项:")
    click.echo("  onescience log <模型别名1>[,<模型别名2>,...] [选项]")
    click.echo("    -tail <行数>    - 显示日志末尾指定行数（默认 50）")
    click.echo("    -head <行数>    - 显示日志开头指定行数")
    click.echo("    -search <关键词> - 搜索日志中包含指定关键词的行")
    click.echo("    -all           - 显示完整日志内容")
    click.echo("    -type <类型>    - 指定日志类型（train/infer/eval/all）")
    click.echo("    -follow        - 实时跟踪日志更新（tail -f）")
    click.echo("    -date <日期>   - 查看指定日期的日志（格式：YYYY-MM-DD）")
    click.echo("    -clean <天数>  - 清理指定天数前的旧日志")
    click.echo("")
    click.echo("data 命令选项:")
    click.echo("  onescience data list [-domain <领域>] [-format <table|json|csv>]")
    click.echo("    -domain   - 按领域筛选数据集")
    click.echo("    -format   - 输出格式（默认 table）")
    click.echo("")
    click.echo("  onescience data info <数据集名称>")
    click.echo("  onescience data download <数据集名称> [-year <年份>] [-output <目录>]")
    click.echo("    -year     - 指定年份（ERA5 数据集）")
    click.echo("    -output   - 输出目录")
    click.echo("")
    click.echo("  onescience data generate <模型别名> [-output <目录>]")
    click.echo("")
    click.echo("deploy 命令选项:")
    click.echo("  onescience deploy export <模型别名> [-format onnx]")
    click.echo("  onescience deploy serve <模型别名> [-port <端口>] [-backend triton]")
    click.echo("    -port     - 服务端口（默认 8000）")
    click.echo("    -backend  - 推理后端（默认 triton）")
    click.echo("")
    click.echo("experiment 命令选项:")
    click.echo("  onescience experiment list [<模型别名>] [-domain <领域>] [-format <table|json|csv>]")
    click.echo("  onescience experiment info <模型别名>")
    click.echo("")
    click.echo("env 命令选项:")
    click.echo("  onescience env list")
    click.echo("  onescience env use [<环境名>]")
    click.echo("  onescience env init [-name <项目名>] [-roots <扫描目录>] [-models-dir <目录>]")
    click.echo("    -name       - 项目名称（默认 my_project）")
    click.echo("    -roots      - 模型扫描目录，逗号分隔")
    click.echo("    -models-dir - 数据集目录")
    click.echo("")
    click.echo("  onescience env info")
    click.echo("")
    click.echo("提示:")
    click.echo("  - 输入数据集名称时，会使用默认路径查找数据集")
    click.echo("  - 输入完整路径时，会直接使用指定的路径")
    click.echo("  - 确保当前账号对指定的数据集路径有访问权限")
    click.echo("")
    click.secho("支持的模型别名:", fg="green")
    for domain_desc, aliases in _GROUPED_ALIASES.items():
        click.secho(f"\n[{domain_desc}]", fg="cyan")
        for alias, model_name in aliases:
            click.echo(f"  {alias:<20} - {model_name}")
    click.echo("  (也支持直接使用模型目录名)")
    click.echo("")
    click.echo("示例:")
    click.echo("  onescience bench -dataset airfoil -models lsm,u_net")
    click.echo("  onescience bench --domain earth                   - 自动用默认数据集跑指定领域")
    click.echo("  onescience bench --domain all                     - 按领域分组自动执行所有模型")
    click.echo("  onescience bench --dir CFD_Benchmark -dataset airfoil - 按模型目录执行")
    click.echo("  onescience train pangu -dataset era5          - 仅训练模型")
    click.echo("  onescience infer pangu -dataset era5          - 仅执行推理")
    click.echo("  onescience eval pangu -dataset era5           - 仅执行评估")
    click.echo("  onescience list models                       - 列出所有模型")
    click.echo("  onescience list models -domain earth -all    - 列出气象领域所有模型")
    click.echo("  onescience list modules                      - 列出所有模块")
    click.echo("  onescience list datasets                     - 列出所有可用数据集")
    click.echo("  onescience list datasets -full               - 扫描数据集目录详细内容")
    click.echo("  onescience info module attention             - 显示 attention 模块信息")
    click.echo("  onescience status pangu                      - 查看模型执行状态")
    click.echo("  onescience config show                       - 查看当前配置")
    click.echo("  onescience config set data_dir /path         - 修改数据集路径")
    click.echo("  onescience log pangu                         - 查看 pangu 模型日志")
    click.echo("  onescience log pangu -clean 7                - 清理7天前的旧日志")
    click.echo("  onescience compare                          - 对比所有已有结果的模型")
    click.echo("  onescience compare pangu,fuxi               - 对比指定模型")
    click.echo("  onescience pipeline -steps \"train fno -dataset airfoil, infer pangu -dataset era5\"")
    click.echo("                                           - 混合编排CFD训练+气象推理")
    click.echo("  onescience pipeline -steps \"train fno, infer pangu\" -dataset era5 -compare")
    click.echo("                                           - 使用默认数据集+执行后对比")
    click.echo("  onescience pipeline -file workflow.txt     - 从文件读取工作流")
    click.echo("  onescience pipeline -on-error skip ...     - 跳过失败步骤继续执行")
    click.echo("  onescience data list                       - 列出所有可用数据集")
    click.echo("  onescience data info era5                  - 显示 ERA5 数据集详情")
    click.echo("  onescience data download era5              - 下载 ERA5 数据")
    click.echo("  onescience data generate pangu             - 生成盘古模型假数据")
    click.echo("  onescience deploy export pangu             - 导出盘古模型为 ONNX")
    click.echo("  onescience deploy serve pangu -port 8000   - 启动推理服务")
    click.echo("  onescience experiment list                  - 列出所有实验记录")
    click.echo("  onescience experiment info pangu            - 查看盘古实验详情")
    click.echo("  onescience config set num_nodes 2          - 设置分布式节点数")
    click.echo("  onescience config set gpus 4               - 设置每节点 GPU 数量")
    click.echo("  onescience env list                        - 列出可用环境")
    click.echo("  onescience env use my_project             - 切换到自定义项目")
    click.echo("  onescience env init -name my_project       - 初始化新项目")
    click.echo("  onescience env info                        - 显示当前环境详情")
    click.echo("  onescience train /path/to/my_model -dataset my_data")
    click.echo("                                           - 直接使用路径执行自定义模型")
