model:

    start_epoch: 0
    max_epoch: 50

    lr: 1E-3

    num_blocks: 8

    in_channels: [  0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 
                    10, 11, 12, 13, 14, 15, 16, 17,
                    18, 19,20,21,22,23,24,25,26,27,
                    28,29,30, 31,32, 33, 34, 35, 36,
                    37, 38, 39,40, 41, 42, 43, 44,
                    45, 46, 47,48, 49, 50, 51, 52,
                    53, 54, 55,56, 57, 58, 59, 60,
                    61, 62, 63,64, 65, 66, 67, 68, 
                    69, 70, 71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96]
    in_chans=96,
    out_channels: [  0,1,4, 5, 6, 7, 8, 9, 
                    10, 11, 12, 13, 14, 15, 16, 17,
                    18, 19,20,21,22,23,24,25,26,27,
                    28,29,30, 31,32, 33, 34, 35, 36,
                    37, 38, 39,40, 41, 42, 43, 44,
                    45, 46, 47,48, 49, 50, 51, 52,
                    53, 54, 55,56, 57, 58, 59, 60,
                    61, 62, 63,64, 65, 66, 67, 68, 
                    69, 70, 71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96]
   
    out_chans=94,
    # channels:  ['10m_u_component_of_wind', '10m_v_component_of_wind', 'zos', 'analysed_sst',

    #           'uo_0.495', 'uo_2.65', 'uo_5.08', 'uo_7.93', 'uo_11.41', 'uo_15.81', 'uo_21.60', 'uo_29.44',
    #             'uo_40.34', 'uo_55.76', 'uo_77.85', 'uo_92.32', 'uo_109.73', 'uo_130.67', 'uo_155.85',
    #             'uo_186.13', 'uo_222.48', 'uo_266.04', 'uo_318.13', 'uo_380.21', 'uo_453.94',
    #             'uo_541.09', 'uo_643.57','vo_0.495', 'vo_2.65', 'vo_5.08', 'vo_7.93', 'vo_11.41', 'vo_15.81', 'vo_21.60', 'vo_29.44',
    #             'vo_40.34', 'vo_55.76', 'vo_77.85', 'vo_92.32', 'vo_109.73', 'vo_130.67', 'vo_155.85',
    #             'vo_186.13', 'vo_222.48', 'vo_266.04', 'vo_318.13', 'vo_380.21', 'vo_453.94',
    #             'vo_541.09', 'vo_643.57','so_0.495', 'so_2.65', 'so_5.08', 'so_7.93', 'so_11.41', 'so_15.81', 'so_21.60', 'so_29.44',
    #             'so_40.34', 'so_55.76', 'so_77.85', 'so_92.32', 'so_109.73', 'so_130.67', 'so_155.85',
    #             'so_186.13', 'so_222.48', 'so_266.04', 'so_318.13', 'so_380.21', 'so_453.94',
    #             'so_541.09', 'so_643.57','thetao_0.495', 'thetao_2.65', 'thetao_5.08', 'thetao_7.93', 'thetao_11.41', 'thetao_15.81', 'thetao_21.60', 'thetao_29.44',
    #             'thetao_40.34', 'thetao_55.76', 'thetao_77.85', 'thetao_92.32', 'thetao_109.73', 'thetao_130.67', 'thetao_155.85',
    #             'thetao_186.13', 'thetao_222.48', 'thetao_266.04', 'thetao_318.13', 'thetao_380.21', 'thetao_453.94',
    #             'thetao_541.09', 'thetao_643.57']
    channels:  [ "sea_surface_temperature","sea_surface_height_above_geoid","10m_u_component_of_wind","10m_v_component_of_wind",
        "eastward_sea_water_velocity_1","eastward_sea_water_velocity_2","eastward_sea_water_velocity_3","eastward_sea_water_velocity_4","eastward_sea_water_velocity_5","eastward_sea_water_velocity_6","eastward_sea_water_velocity_7","eastward_sea_water_velocity_8","eastward_sea_water_velocity_9","eastward_sea_water_velocity_10","eastward_sea_water_velocity_11","eastward_sea_water_velocity_12","eastward_sea_water_velocity_13","eastward_sea_water_velocity_14","eastward_sea_water_velocity_15","eastward_sea_water_velocity_16","eastward_sea_water_velocity_17","eastward_sea_water_velocity_18","eastward_sea_water_velocity_19","eastward_sea_water_velocity_20","eastward_sea_water_velocity_21","eastward_sea_water_velocity_22","eastward_sea_water_velocity_23","northward_sea_water_velocity_1","northward_sea_water_velocity_2","northward_sea_water_velocity_3","northward_sea_water_velocity_4","northward_sea_water_velocity_5","northward_sea_water_velocity_6","northward_sea_water_velocity_7","northward_sea_water_velocity_8","northward_sea_water_velocity_9","northward_sea_water_velocity_10","northward_sea_water_velocity_11","northward_sea_water_velocity_12","northward_sea_water_velocity_13","northward_sea_water_velocity_14","northward_sea_water_velocity_15","northward_sea_water_velocity_16","northward_sea_water_velocity_17","northward_sea_water_velocity_18","northward_sea_water_velocity_19","northward_sea_water_velocity_20","northward_sea_water_velocity_21","northward_sea_water_velocity_22","northward_sea_water_velocity_23",
        "sea_water_salinity_1","sea_water_salinity_2","sea_water_salinity_3","sea_water_salinity_4","sea_water_salinity_5","sea_water_salinity_6","sea_water_salinity_7","sea_water_salinity_8","sea_water_salinity_9","sea_water_salinity_10","sea_water_salinity_11","sea_water_salinity_12","sea_water_salinity_13","sea_water_salinity_14","sea_water_salinity_15","sea_water_salinity_16","sea_water_salinity_17","sea_water_salinity_18","sea_water_salinity_19","sea_water_salinity_20","sea_water_salinity_21","sea_water_salinity_22","sea_water_salinity_23",
        "sea_water_potential_temperature_1","sea_water_potential_temperature_2","sea_water_potential_temperature_3","sea_water_potential_temperature_4","sea_water_potential_temperature_5","sea_water_potential_temperature_6","sea_water_potential_temperature_7","sea_water_potential_temperature_8","sea_water_potential_temperature_9","sea_water_potential_temperature_10","sea_water_potential_temperature_11","sea_water_potential_temperature_12","sea_water_potential_temperature_13","sea_water_potential_temperature_14","sea_water_potential_temperature_15","sea_water_potential_temperature_16","sea_water_potential_temperature_17","sea_water_potential_temperature_18","sea_water_potential_temperature_19","sea_water_potential_temperature_20","sea_water_potential_temperature_21","sea_water_potential_temperature_22","sea_water_potential_temperature_23"]
    time_res: 24

    img_size: [721, 1440]
    patch_size: [6, 12]

    num_samples_per_year: None
    num_steps: 1

    mask_dtype: "float32"
    batch_size: 1
    num_workers: 4
    patience: 50

    checkpoint_dir : "./data/checkpoints"
    stats_dir: './data/stats' # "/public/onestore/onedatasets/ERA5/newh5/stats/" 
    static_dir: "./data/static/" # "/public/onestore/onedatasets/ERA5/newh5/static/" 
    data_dir: ./data/ # "/public/onestore/onedatasets/ERA5/newh5" 
    mask_dir: "./public/home/onescience2025404/hanym/onescience/examples/earth/xihe/20210628_zos_ocean_mask.npy"
    train_ratio: 0.6
    val_ratio: 0.2
    test_ratio: 0.2





